source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

pod 'CocoaLumberjack'
pod 'mqttc/MinL', :path => '~/mqttc'
pod 'mqttc/WebsocketL', :path => '~/mqttc'

target 'MQTTInspector' do
end

